### ISSUE TITLE
Додати документацію

### ISSUE THREAD

**Issue by kroman0** [openprocurement/openprocurement.integrations.edr#12]
Потрібно додати документацію по протоколу взаємодії з проксі
@Krokop

**Comment by Krokop** [comment]
Поки не буде фіналізоване ТЗ, можно почекати з документацією.

**Comment by Krokop** [comment]
@kroman0 ПР з документацією https://github.com/openprocurement/openprocurement.integrations.edr/pull/15

**Comment by kroman0** [comment]
В документації вказано `/api/1.0/verify` але проксі відповідає на `/verify`

**Comment by Krokop** [comment]
Так, але була домовленість, що версійність необхідна(на даний момент версійність буде за допомогою nginx)
Останній варіант відповіді від proxy -
https://docs.google.com/document/d/109MlTM8f8NS9duhwP9mByFz0mEd1yyQCQ_7_Ki6Cq9k/edit

**Comment by kroman0** [comment]
#17 потребує оновлення документації

**Comment by Krokop** [comment]
Це можна закривати?

**Comment by kroman0** [comment]
Потрібно описати помилки щоб виникало менше питань при їх виникненні. Найдоцільніше описати в формі: помилка(код, відповідь) - опис - подальші дії(як уникнути чи як виправити чи що перевірити).

**Comment by Krokop** [comment]
https://github.com/openprocurement/openprocurement.integrations.edr/pull/27#event-1043065730

**Comment by Krokop** [comment]
@kroman0 дока повна або ще чогось не вистачає?
